// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sorriso_em_Jogo.Infrastructure.Data;

#nullable disable

namespace Sorriso_em_Jogo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroHabito", b =>
                {
                    b.Property<int>("Id_habito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_habito"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("HabitoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id_habito");

                    b.HasIndex("HabitoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroHabito");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Feedback", b =>
                {
                    b.Property<int>("Id_feedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_feedback"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id_feedback");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Habito", b =>
                {
                    b.Property<int>("Id_habito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_habito"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<float>("Frequencia_ideal")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id_habito");

                    b.ToTable("Habito");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Procedimento", b =>
                {
                    b.Property<int>("Id_procedimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_procedimento"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id_procedimento");

                    b.ToTable("Procedimento");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.ProcedimentosDaUnidade", b =>
                {
                    b.Property<int>("UnidadeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnOrder(0);

                    b.Property<int>("ProcedimentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnOrder(1);

                    b.HasKey("UnidadeId", "ProcedimentoId");

                    b.HasIndex("ProcedimentoId");

                    b.ToTable("ProcedimentosDaUnidade");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Recompensa", b =>
                {
                    b.Property<int>("Id_recompensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_recompensa"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<float>("Pontos_necessarios")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("Id_recompensa");

                    b.ToTable("Recompensa");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Unidade", b =>
                {
                    b.Property<int>("Id_unidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_unidade"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id_unidade");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Usuario", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_usuario"));

                    b.Property<DateTime>("Data_cadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<float?>("Pontos_recompensa")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("Pontos_recompensa");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id_usuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.UsuarioColetandoRecompensa", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("UsuarioId");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RecompensaId");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DataColeta");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("UsuarioId", "RecompensaId");

                    b.HasIndex("RecompensaId");

                    b.ToTable("UsuarioColetandoRecompensa");
                });

            modelBuilder.Entity("RegistroHabito", b =>
                {
                    b.HasOne("Sorriso_em_Jogo.Models.Habito", "Habito")
                        .WithMany("RegistrosHabito")
                        .HasForeignKey("HabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sorriso_em_Jogo.Models.Usuario", "Usuario")
                        .WithMany("RegistrosHabito")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Feedback", b =>
                {
                    b.HasOne("Sorriso_em_Jogo.Models.Usuario", "Usuario")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.ProcedimentosDaUnidade", b =>
                {
                    b.HasOne("Sorriso_em_Jogo.Models.Procedimento", "Procedimento")
                        .WithMany("ProcedimentosDaUnidade")
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sorriso_em_Jogo.Models.Unidade", "Unidade")
                        .WithMany("ProcedimentosDaUnidade")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procedimento");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.UsuarioColetandoRecompensa", b =>
                {
                    b.HasOne("Sorriso_em_Jogo.Models.Recompensa", "Recompensa")
                        .WithMany("UsuariosColetandoRecompensa")
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sorriso_em_Jogo.Models.Usuario", "Usuario")
                        .WithMany("RecompensasColetadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recompensa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Habito", b =>
                {
                    b.Navigation("RegistrosHabito");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Procedimento", b =>
                {
                    b.Navigation("ProcedimentosDaUnidade");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Recompensa", b =>
                {
                    b.Navigation("UsuariosColetandoRecompensa");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Unidade", b =>
                {
                    b.Navigation("ProcedimentosDaUnidade");
                });

            modelBuilder.Entity("Sorriso_em_Jogo.Models.Usuario", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("RecompensasColetadas");

                    b.Navigation("RegistrosHabito");
                });
#pragma warning restore 612, 618
        }
    }
}
